### ISSUE TITLE
Create a github project for Corporate Hellscape

### ISSUE THREAD

**Issue by JMarlin** [LaurenEBaker/Corprate_Hellscape#18]
- Go to your profile and then the 'Projects' tab
- Click the 'new project' button
- Use the 'Team Backlog' project template
- Go to the Corporate_Hellscape repo and then to *its* Projects tab
- Link the new project to the repo

**Comment by LaurenEBaker** [comment]
all set

**Comment by JMarlin** [comment]
I have never actually used github projects (all of my day job kanbans have been in Azure Dev Ops), so this should be fun
