### ISSUE TITLE
refine character class with min max and set values

### ISSUE THREAD

**Issue by MoAlsa7** [LaurenEBaker/Corprate_Hellscape#36]
- [ ] Adding a few more attributes to character class like boredom to decrease the fun level and sleep
- [ ] Set max values for the increase methods 
- [ ] Trigger game over when character health hits zero

**Comment by JMarlin** [comment]
@MoAlsa7, updated your description. Moving the new events to their own separate issue.

**Comment by JMarlin** [comment]
New events issue is #38
