### ISSUE TITLE
Define initial character class

### ISSUE THREAD

**Issue by JMarlin** [LaurenEBaker/Corprate_Hellscape#4]
Define the basic character class

This depends on the skeleton from #3 

No one is going to use any fields/methods you define yet (story #3 will simply call new on the class)
Please use this story to play with an initial idea of what features the 'character' can have

**Comment by JMarlin** [comment]
#3 closed, ready to go

**Comment by Jax47** [comment]
Added and defined a basic character class. Pull Request was approved. Changed has been merged into the main. Closing the issues. 

[The PR mention](https://github.com/LaurenEBaker/Corprate_Hellscape/pull/19)
