### ISSUE TITLE
Update ALL usages of the player increase/decrease stat methods

### ISSUE THREAD

**Issue by JMarlin** [LaurenEBaker/Corprate_Hellscape#66]
Currently, doing a `mvn clean package` will not successfully compile the project as there are still references to `increaseX`/`decreaseX` methods without passing in the new amount parameter.

**Comment by LaurenEBaker** [comment]
In the  new status event classes and check_ classes, increaseX or decreaseX is being called but there’s no input for the amount by which it’s going to do the action, is this the issue or is it something else?

**Comment by JMarlin** [comment]
Yeah, that's exactly the issue.
You could go through and update all of those method calls, or -- and this would be way easier -- just update the definition of the method so its argument has a default value of 1

**Comment by JMarlin** [comment]
And as far as the not being familiar with Maven, that's understandable and pretty much the story for everyone
